# based on https://github.com/mvdan/github-actions-golang
name: Lint

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request: {}

  # Scan all files on branches, block on any issues
  push:
    branches: ["main"]

#   Schedule this job to run at a certain time, using cron syntax
#   Note that * is a special character in YAML so you have to quote this string
#  schedule:
#    - cron: '*/60 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install the `buf` CLI
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1

      # Lint your Protobuf sources
      - name: Lint proto files
        uses: bufbuild/buf-lint-action@v1

#      - name: Detect breaking changes
#        uses: bufbuild/buf-breaking-action@v1
#        with:
#          against: 'https://github.com/acme/weather.git#branch=main'