// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: integrations/integrations/v1/messages.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _messages_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetIntegrationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIntegrationsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIntegrationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIntegrationsRequestMultiError, or nil if none found.
func (m *GetIntegrationsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIntegrationsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOwnerId()); err != nil {
		err = GetIntegrationsRequestValidationError{
			field:  "OwnerId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetIntegrationsRequestMultiError(errors)
	}

	return nil
}

func (m *GetIntegrationsRequest) _validateUuid(uuid string) error {
	if matched := _messages_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetIntegrationsRequestMultiError is an error wrapping multiple validation
// errors returned by GetIntegrationsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetIntegrationsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIntegrationsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIntegrationsRequestMultiError) AllErrors() []error { return m }

// GetIntegrationsRequestValidationError is the validation error returned by
// GetIntegrationsRequest.Validate if the designated constraints aren't met.
type GetIntegrationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIntegrationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIntegrationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIntegrationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIntegrationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIntegrationsRequestValidationError) ErrorName() string {
	return "GetIntegrationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetIntegrationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIntegrationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIntegrationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIntegrationsRequestValidationError{}

// Validate checks the field values on GetIntegrationsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIntegrationsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIntegrationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIntegrationsResponseMultiError, or nil if none found.
func (m *GetIntegrationsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIntegrationsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIntegrationsResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIntegrationsResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIntegrationsResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetIntegrations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetIntegrationsResponseValidationError{
						field:  fmt.Sprintf("Integrations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetIntegrationsResponseValidationError{
						field:  fmt.Sprintf("Integrations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetIntegrationsResponseValidationError{
					field:  fmt.Sprintf("Integrations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetIntegrationsResponseMultiError(errors)
	}

	return nil
}

// GetIntegrationsResponseMultiError is an error wrapping multiple validation
// errors returned by GetIntegrationsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetIntegrationsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIntegrationsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIntegrationsResponseMultiError) AllErrors() []error { return m }

// GetIntegrationsResponseValidationError is the validation error returned by
// GetIntegrationsResponse.Validate if the designated constraints aren't met.
type GetIntegrationsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIntegrationsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIntegrationsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIntegrationsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIntegrationsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIntegrationsResponseValidationError) ErrorName() string {
	return "GetIntegrationsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetIntegrationsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIntegrationsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIntegrationsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIntegrationsResponseValidationError{}

// Validate checks the field values on RegisterIntegrationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterIntegrationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterIntegrationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterIntegrationRequestMultiError, or nil if none found.
func (m *RegisterIntegrationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterIntegrationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOwnerId()); err != nil {
		err = RegisterIntegrationRequestValidationError{
			field:  "OwnerId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetTypeId()); err != nil {
		err = RegisterIntegrationRequestValidationError{
			field:  "TypeId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegisterIntegrationRequestMultiError(errors)
	}

	return nil
}

func (m *RegisterIntegrationRequest) _validateUuid(uuid string) error {
	if matched := _messages_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RegisterIntegrationRequestMultiError is an error wrapping multiple
// validation errors returned by RegisterIntegrationRequest.ValidateAll() if
// the designated constraints aren't met.
type RegisterIntegrationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterIntegrationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterIntegrationRequestMultiError) AllErrors() []error { return m }

// RegisterIntegrationRequestValidationError is the validation error returned
// by RegisterIntegrationRequest.Validate if the designated constraints aren't met.
type RegisterIntegrationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterIntegrationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterIntegrationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterIntegrationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterIntegrationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterIntegrationRequestValidationError) ErrorName() string {
	return "RegisterIntegrationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterIntegrationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterIntegrationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterIntegrationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterIntegrationRequestValidationError{}

// Validate checks the field values on RegisterIntegrationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterIntegrationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterIntegrationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterIntegrationResponseMultiError, or nil if none found.
func (m *RegisterIntegrationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterIntegrationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterIntegrationResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterIntegrationResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterIntegrationResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetIntegration()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterIntegrationResponseValidationError{
					field:  "Integration",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterIntegrationResponseValidationError{
					field:  "Integration",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIntegration()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterIntegrationResponseValidationError{
				field:  "Integration",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RegisterIntegrationResponseMultiError(errors)
	}

	return nil
}

// RegisterIntegrationResponseMultiError is an error wrapping multiple
// validation errors returned by RegisterIntegrationResponse.ValidateAll() if
// the designated constraints aren't met.
type RegisterIntegrationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterIntegrationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterIntegrationResponseMultiError) AllErrors() []error { return m }

// RegisterIntegrationResponseValidationError is the validation error returned
// by RegisterIntegrationResponse.Validate if the designated constraints
// aren't met.
type RegisterIntegrationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterIntegrationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterIntegrationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterIntegrationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterIntegrationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterIntegrationResponseValidationError) ErrorName() string {
	return "RegisterIntegrationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterIntegrationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterIntegrationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterIntegrationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterIntegrationResponseValidationError{}

// Validate checks the field values on RegisterIntegrationPropertiesRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *RegisterIntegrationPropertiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterIntegrationPropertiesRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// RegisterIntegrationPropertiesRequestMultiError, or nil if none found.
func (m *RegisterIntegrationPropertiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterIntegrationPropertiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetIntegrationId()); err != nil {
		err = RegisterIntegrationPropertiesRequestValidationError{
			field:  "IntegrationId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetProperties() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RegisterIntegrationPropertiesRequestValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RegisterIntegrationPropertiesRequestValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RegisterIntegrationPropertiesRequestValidationError{
					field:  fmt.Sprintf("Properties[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RegisterIntegrationPropertiesRequestMultiError(errors)
	}

	return nil
}

func (m *RegisterIntegrationPropertiesRequest) _validateUuid(uuid string) error {
	if matched := _messages_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RegisterIntegrationPropertiesRequestMultiError is an error wrapping multiple
// validation errors returned by
// RegisterIntegrationPropertiesRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterIntegrationPropertiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterIntegrationPropertiesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterIntegrationPropertiesRequestMultiError) AllErrors() []error { return m }

// RegisterIntegrationPropertiesRequestValidationError is the validation error
// returned by RegisterIntegrationPropertiesRequest.Validate if the designated
// constraints aren't met.
type RegisterIntegrationPropertiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterIntegrationPropertiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterIntegrationPropertiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterIntegrationPropertiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterIntegrationPropertiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterIntegrationPropertiesRequestValidationError) ErrorName() string {
	return "RegisterIntegrationPropertiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterIntegrationPropertiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterIntegrationPropertiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterIntegrationPropertiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterIntegrationPropertiesRequestValidationError{}

// Validate checks the field values on RegisterIntegrationPropertiesResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *RegisterIntegrationPropertiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterIntegrationPropertiesResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// RegisterIntegrationPropertiesResponseMultiError, or nil if none found.
func (m *RegisterIntegrationPropertiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterIntegrationPropertiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterIntegrationPropertiesResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterIntegrationPropertiesResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterIntegrationPropertiesResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RegisterIntegrationPropertiesResponseMultiError(errors)
	}

	return nil
}

// RegisterIntegrationPropertiesResponseMultiError is an error wrapping
// multiple validation errors returned by
// RegisterIntegrationPropertiesResponse.ValidateAll() if the designated
// constraints aren't met.
type RegisterIntegrationPropertiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterIntegrationPropertiesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterIntegrationPropertiesResponseMultiError) AllErrors() []error { return m }

// RegisterIntegrationPropertiesResponseValidationError is the validation error
// returned by RegisterIntegrationPropertiesResponse.Validate if the
// designated constraints aren't met.
type RegisterIntegrationPropertiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterIntegrationPropertiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterIntegrationPropertiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterIntegrationPropertiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterIntegrationPropertiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterIntegrationPropertiesResponseValidationError) ErrorName() string {
	return "RegisterIntegrationPropertiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterIntegrationPropertiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterIntegrationPropertiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterIntegrationPropertiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterIntegrationPropertiesResponseValidationError{}

// Validate checks the field values on GetIntegrationPropertiesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIntegrationPropertiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIntegrationPropertiesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetIntegrationPropertiesRequestMultiError, or nil if none found.
func (m *GetIntegrationPropertiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIntegrationPropertiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetIntegrationId()); err != nil {
		err = GetIntegrationPropertiesRequestValidationError{
			field:  "IntegrationId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetIntegrationPropertiesRequestMultiError(errors)
	}

	return nil
}

func (m *GetIntegrationPropertiesRequest) _validateUuid(uuid string) error {
	if matched := _messages_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetIntegrationPropertiesRequestMultiError is an error wrapping multiple
// validation errors returned by GetIntegrationPropertiesRequest.ValidateAll()
// if the designated constraints aren't met.
type GetIntegrationPropertiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIntegrationPropertiesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIntegrationPropertiesRequestMultiError) AllErrors() []error { return m }

// GetIntegrationPropertiesRequestValidationError is the validation error
// returned by GetIntegrationPropertiesRequest.Validate if the designated
// constraints aren't met.
type GetIntegrationPropertiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIntegrationPropertiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIntegrationPropertiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIntegrationPropertiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIntegrationPropertiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIntegrationPropertiesRequestValidationError) ErrorName() string {
	return "GetIntegrationPropertiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetIntegrationPropertiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIntegrationPropertiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIntegrationPropertiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIntegrationPropertiesRequestValidationError{}

// Validate checks the field values on GetIntegrationPropertiesResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetIntegrationPropertiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIntegrationPropertiesResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetIntegrationPropertiesResponseMultiError, or nil if none found.
func (m *GetIntegrationPropertiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIntegrationPropertiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIntegrationPropertiesResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIntegrationPropertiesResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIntegrationPropertiesResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetProperties() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetIntegrationPropertiesResponseValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetIntegrationPropertiesResponseValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetIntegrationPropertiesResponseValidationError{
					field:  fmt.Sprintf("Properties[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetIntegrationPropertiesResponseMultiError(errors)
	}

	return nil
}

// GetIntegrationPropertiesResponseMultiError is an error wrapping multiple
// validation errors returned by
// GetIntegrationPropertiesResponse.ValidateAll() if the designated
// constraints aren't met.
type GetIntegrationPropertiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIntegrationPropertiesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIntegrationPropertiesResponseMultiError) AllErrors() []error { return m }

// GetIntegrationPropertiesResponseValidationError is the validation error
// returned by GetIntegrationPropertiesResponse.Validate if the designated
// constraints aren't met.
type GetIntegrationPropertiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIntegrationPropertiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIntegrationPropertiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIntegrationPropertiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIntegrationPropertiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIntegrationPropertiesResponseValidationError) ErrorName() string {
	return "GetIntegrationPropertiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetIntegrationPropertiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIntegrationPropertiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIntegrationPropertiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIntegrationPropertiesResponseValidationError{}

// Validate checks the field values on RemoveIntegrationPropertiesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *RemoveIntegrationPropertiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveIntegrationPropertiesRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// RemoveIntegrationPropertiesRequestMultiError, or nil if none found.
func (m *RemoveIntegrationPropertiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveIntegrationPropertiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetIntegrationId()); err != nil {
		err = RemoveIntegrationPropertiesRequestValidationError{
			field:  "IntegrationId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := len(m.GetPropertyIds()); l < 1 || l > 100 {
		err := RemoveIntegrationPropertiesRequestValidationError{
			field:  "PropertyIds",
			reason: "value must contain between 1 and 100 items, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	_RemoveIntegrationPropertiesRequest_PropertyIds_Unique := make(map[string]struct{}, len(m.GetPropertyIds()))

	for idx, item := range m.GetPropertyIds() {
		_, _ = idx, item

		if _, exists := _RemoveIntegrationPropertiesRequest_PropertyIds_Unique[item]; exists {
			err := RemoveIntegrationPropertiesRequestValidationError{
				field:  fmt.Sprintf("PropertyIds[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_RemoveIntegrationPropertiesRequest_PropertyIds_Unique[item] = struct{}{}
		}

		if err := m._validateUuid(item); err != nil {
			err = RemoveIntegrationPropertiesRequestValidationError{
				field:  fmt.Sprintf("PropertyIds[%v]", idx),
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return RemoveIntegrationPropertiesRequestMultiError(errors)
	}

	return nil
}

func (m *RemoveIntegrationPropertiesRequest) _validateUuid(uuid string) error {
	if matched := _messages_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RemoveIntegrationPropertiesRequestMultiError is an error wrapping multiple
// validation errors returned by
// RemoveIntegrationPropertiesRequest.ValidateAll() if the designated
// constraints aren't met.
type RemoveIntegrationPropertiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveIntegrationPropertiesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveIntegrationPropertiesRequestMultiError) AllErrors() []error { return m }

// RemoveIntegrationPropertiesRequestValidationError is the validation error
// returned by RemoveIntegrationPropertiesRequest.Validate if the designated
// constraints aren't met.
type RemoveIntegrationPropertiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveIntegrationPropertiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveIntegrationPropertiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveIntegrationPropertiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveIntegrationPropertiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveIntegrationPropertiesRequestValidationError) ErrorName() string {
	return "RemoveIntegrationPropertiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveIntegrationPropertiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveIntegrationPropertiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveIntegrationPropertiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveIntegrationPropertiesRequestValidationError{}

// Validate checks the field values on RemoveIntegrationPropertiesResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *RemoveIntegrationPropertiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveIntegrationPropertiesResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// RemoveIntegrationPropertiesResponseMultiError, or nil if none found.
func (m *RemoveIntegrationPropertiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveIntegrationPropertiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RemoveIntegrationPropertiesResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RemoveIntegrationPropertiesResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RemoveIntegrationPropertiesResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RemoveIntegrationPropertiesResponseMultiError(errors)
	}

	return nil
}

// RemoveIntegrationPropertiesResponseMultiError is an error wrapping multiple
// validation errors returned by
// RemoveIntegrationPropertiesResponse.ValidateAll() if the designated
// constraints aren't met.
type RemoveIntegrationPropertiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveIntegrationPropertiesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveIntegrationPropertiesResponseMultiError) AllErrors() []error { return m }

// RemoveIntegrationPropertiesResponseValidationError is the validation error
// returned by RemoveIntegrationPropertiesResponse.Validate if the designated
// constraints aren't met.
type RemoveIntegrationPropertiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveIntegrationPropertiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveIntegrationPropertiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveIntegrationPropertiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveIntegrationPropertiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveIntegrationPropertiesResponseValidationError) ErrorName() string {
	return "RemoveIntegrationPropertiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveIntegrationPropertiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveIntegrationPropertiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveIntegrationPropertiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveIntegrationPropertiesResponseValidationError{}
