// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: integrations/integrations/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Service_GetIntegrations_FullMethodName               = "/integrations.integrations.v1.Service/GetIntegrations"
	Service_RegisterIntegration_FullMethodName           = "/integrations.integrations.v1.Service/RegisterIntegration"
	Service_RegisterIntegrationProperties_FullMethodName = "/integrations.integrations.v1.Service/RegisterIntegrationProperties"
	Service_GetIntegrationProperties_FullMethodName      = "/integrations.integrations.v1.Service/GetIntegrationProperties"
	Service_UpdateIntegrationProperty_FullMethodName     = "/integrations.integrations.v1.Service/UpdateIntegrationProperty"
	Service_RemoveIntegrationProperty_FullMethodName     = "/integrations.integrations.v1.Service/RemoveIntegrationProperty"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	GetIntegrations(ctx context.Context, in *GetIntegrationsRequest, opts ...grpc.CallOption) (*GetIntegrationsResponse, error)
	RegisterIntegration(ctx context.Context, in *RegisterIntegrationRequest, opts ...grpc.CallOption) (*RegisterIntegrationResponse, error)
	RegisterIntegrationProperties(ctx context.Context, in *RegisterIntegrationPropertiesRequest, opts ...grpc.CallOption) (*RegisterIntegrationPropertiesResponse, error)
	GetIntegrationProperties(ctx context.Context, in *GetIntegrationPropertiesRequest, opts ...grpc.CallOption) (*GetIntegrationPropertiesResponse, error)
	UpdateIntegrationProperty(ctx context.Context, in *UpdateIntegrationPropertyRequest, opts ...grpc.CallOption) (*UpdateIntegrationPropertyResponse, error)
	RemoveIntegrationProperty(ctx context.Context, in *RemoveIntegrationPropertyRequest, opts ...grpc.CallOption) (*RemoveIntegrationPropertyResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetIntegrations(ctx context.Context, in *GetIntegrationsRequest, opts ...grpc.CallOption) (*GetIntegrationsResponse, error) {
	out := new(GetIntegrationsResponse)
	err := c.cc.Invoke(ctx, Service_GetIntegrations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) RegisterIntegration(ctx context.Context, in *RegisterIntegrationRequest, opts ...grpc.CallOption) (*RegisterIntegrationResponse, error) {
	out := new(RegisterIntegrationResponse)
	err := c.cc.Invoke(ctx, Service_RegisterIntegration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) RegisterIntegrationProperties(ctx context.Context, in *RegisterIntegrationPropertiesRequest, opts ...grpc.CallOption) (*RegisterIntegrationPropertiesResponse, error) {
	out := new(RegisterIntegrationPropertiesResponse)
	err := c.cc.Invoke(ctx, Service_RegisterIntegrationProperties_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetIntegrationProperties(ctx context.Context, in *GetIntegrationPropertiesRequest, opts ...grpc.CallOption) (*GetIntegrationPropertiesResponse, error) {
	out := new(GetIntegrationPropertiesResponse)
	err := c.cc.Invoke(ctx, Service_GetIntegrationProperties_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpdateIntegrationProperty(ctx context.Context, in *UpdateIntegrationPropertyRequest, opts ...grpc.CallOption) (*UpdateIntegrationPropertyResponse, error) {
	out := new(UpdateIntegrationPropertyResponse)
	err := c.cc.Invoke(ctx, Service_UpdateIntegrationProperty_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) RemoveIntegrationProperty(ctx context.Context, in *RemoveIntegrationPropertyRequest, opts ...grpc.CallOption) (*RemoveIntegrationPropertyResponse, error) {
	out := new(RemoveIntegrationPropertyResponse)
	err := c.cc.Invoke(ctx, Service_RemoveIntegrationProperty_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	GetIntegrations(context.Context, *GetIntegrationsRequest) (*GetIntegrationsResponse, error)
	RegisterIntegration(context.Context, *RegisterIntegrationRequest) (*RegisterIntegrationResponse, error)
	RegisterIntegrationProperties(context.Context, *RegisterIntegrationPropertiesRequest) (*RegisterIntegrationPropertiesResponse, error)
	GetIntegrationProperties(context.Context, *GetIntegrationPropertiesRequest) (*GetIntegrationPropertiesResponse, error)
	UpdateIntegrationProperty(context.Context, *UpdateIntegrationPropertyRequest) (*UpdateIntegrationPropertyResponse, error)
	RemoveIntegrationProperty(context.Context, *RemoveIntegrationPropertyRequest) (*RemoveIntegrationPropertyResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) GetIntegrations(context.Context, *GetIntegrationsRequest) (*GetIntegrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrations not implemented")
}
func (UnimplementedServiceServer) RegisterIntegration(context.Context, *RegisterIntegrationRequest) (*RegisterIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterIntegration not implemented")
}
func (UnimplementedServiceServer) RegisterIntegrationProperties(context.Context, *RegisterIntegrationPropertiesRequest) (*RegisterIntegrationPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterIntegrationProperties not implemented")
}
func (UnimplementedServiceServer) GetIntegrationProperties(context.Context, *GetIntegrationPropertiesRequest) (*GetIntegrationPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrationProperties not implemented")
}
func (UnimplementedServiceServer) UpdateIntegrationProperty(context.Context, *UpdateIntegrationPropertyRequest) (*UpdateIntegrationPropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIntegrationProperty not implemented")
}
func (UnimplementedServiceServer) RemoveIntegrationProperty(context.Context, *RemoveIntegrationPropertyRequest) (*RemoveIntegrationPropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIntegrationProperty not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetIntegrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetIntegrations(ctx, req.(*GetIntegrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_RegisterIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RegisterIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_RegisterIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RegisterIntegration(ctx, req.(*RegisterIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_RegisterIntegrationProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterIntegrationPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RegisterIntegrationProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_RegisterIntegrationProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RegisterIntegrationProperties(ctx, req.(*RegisterIntegrationPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetIntegrationProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetIntegrationProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetIntegrationProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetIntegrationProperties(ctx, req.(*GetIntegrationPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpdateIntegrationProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIntegrationPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpdateIntegrationProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UpdateIntegrationProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpdateIntegrationProperty(ctx, req.(*UpdateIntegrationPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_RemoveIntegrationProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIntegrationPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RemoveIntegrationProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_RemoveIntegrationProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RemoveIntegrationProperty(ctx, req.(*RemoveIntegrationPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integrations.integrations.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIntegrations",
			Handler:    _Service_GetIntegrations_Handler,
		},
		{
			MethodName: "RegisterIntegration",
			Handler:    _Service_RegisterIntegration_Handler,
		},
		{
			MethodName: "RegisterIntegrationProperties",
			Handler:    _Service_RegisterIntegrationProperties_Handler,
		},
		{
			MethodName: "GetIntegrationProperties",
			Handler:    _Service_GetIntegrationProperties_Handler,
		},
		{
			MethodName: "UpdateIntegrationProperty",
			Handler:    _Service_UpdateIntegrationProperty_Handler,
		},
		{
			MethodName: "RemoveIntegrationProperty",
			Handler:    _Service_RemoveIntegrationProperty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integrations/integrations/v1/service.proto",
}
